@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow

Class StatusBarFooter
Class FeedbackDisplay
Class CommandBox
Class HelpWindow

Class OverallStatistics

' Class DisplayListPanel
' Class PetCard
' Class SlotCard
' Class FoodCollectionCard
' Class FoodAmountAndPetCard

package Calendar <<Rectangle>> {
Class HiddenCalendar #FFFFFF
}

package DisplayList <<Rectangle>> {
Class HiddenDisplayList #FFFFFF
}

}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .up.|> Ui
UiManager -down-> MainWindow

UiManager --> Logic
MainWindow -down-> Logic

MainWindow *-up-> StatusBarFooter
MainWindow *-up-> FeedbackDisplay
MainWindow *-up-> CommandBox
MainWindow *-up-> HelpWindow

MainWindow -up-|> UiPart
StatusBarFooter -up-|> UiPart
FeedbackDisplay -up-|> UiPart
CommandBox -up-|> UiPart
HelpWindow -up-|> UiPart


MainWindow *--> OverallStatistics
OverallStatistics .down.> Model
OverallStatistics -up-|> UiPart

MainWindow *--> DisplayList
DisplayList ..> Model
' MainWindow *--> DisplayListPanel

' DisplayListPanel --> PetCard
' DisplayListPanel --> SlotCard
' DisplayListPanel --> FoodCollectionCard
' DisplayListPanel --> FoodAmountAndPetCard

' PetCard --|> UiPart2
' SlotCard --|> UiPart2
' FoodCollectionCard --|> UiPart2
' FoodAmountAndPetCard --|> UiPart2

' PetCard ...> Model
' SlotCard ...> Model
' FoodCollectionCard ...> Model
' FoodAmountAndPetCard ...> Model

MainWindow *--> Calendar
Calendar ..> Model
@enduml