@startuml
!include ../style.puml

(*)  --> "PetTrackerParser matches command `findslots`"
--> "Initialize new FindSlotCommandParser"
if "[if both name prefix and dateTime prefix are empty]" then
--> [then] "throw new parse exception"
else
--> [ else] "check for names in argMultimap"
if "[if name prefix is present]" then
--> [then] "add new SlotPetNamePredicate to list of predicates"
--> "check for dateTime in argMultimap"
else
--> [ else] "check for dateTime in argMultimap"
if "dateTime prefix is present"
--> [then] "add new SlotDatePredicate to list of predicates"
--> "reduce list of predicates with Predicate::and"
else
--> [ else] "reduce list of predicates with Predicate::and"
endif
endif
endif
--> "return new FindSlotCommand"
-->(*)
@enduml
