@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyPetTracker <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class PetTracker
Class ReadOnlyPetTracker
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class UniquePetList

Package Pet {
Class Pet
Class DateOfBirth
Class Food
Class Gender
Class Name
Class Species
Class Tag

}

Package Schedule {
Class Schedule
Class Slot
Class DateTime
Class SlotDuration
}

Package FoodCollection {
Class FoodCollection
Class FoodCollectionList
Class FoodAmountAndPet
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

PetTracker .up.|> ReadOnlyPetTracker

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" PetTracker
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

PetTracker *--> "1" UniquePetList
UniquePetList o--> "*" Pet
UniquePetList o--> "1" FoodCollectionList
FoodCollectionList o--> "*" FoodCollection
FoodCollection *--> "1..*" FoodAmountAndPet

Pet *--> "1" Name
Pet *--> "1" Species
Pet *--> "1" DateOfBirth
Pet *--> "1" Gender
Pet *--> "1..*" Food
Pet *--> "*" Tag

Name -[hidden]right-> DateOfBirth
DateOfBirth -[hidden]right-> Gender
Species -[hidden]right-> Food

UniquePetList o--> "1" Schedule


Schedule o--> "*" Slot
Slot o--> "1" Pet
Slot *--> "1" SlotDuration
Slot *--> "1" DateTime

ModelManager o-->"1" Pet : filtered list
ModelManager o-->"1" Slot : filtered list
ModelManager o-->"1" FoodCollection : filtered list



@enduml
