@startuml
!include ../style.puml

skinparam ParticipantPadding 45

box Model MODEL_COLOR_T1
participant ":UniquePetList" as UniquePetList MODEL_COLOR
participant ":PetListChangeListener" as PetListChangeListener MODEL_COLOR
participant ":Schedule" as Schedule MODEL_COLOR
end box

[-> UniquePetList : deletePet(1)
activate UniquePetList

UniquePetList -> PetListChangeListener : onChanged(petChange)
activate PetListChangeListener

PetListChangeListener -> PetListChangeListener : removeExcessSlot

PetListChangeListener -> Schedule : remove(slot)
activate Schedule

Schedule -> Schedule : internalList\n.remove(slot)

Schedule --> PetListChangeListener
deactivate Schedule

PetListChangeListener --> UniquePetList
deactivate PetListChangeListener

[<--UniquePetList
deactivate UniquePetList
@enduml
